cmd/deploy.go

This PR adds the '-q' flag to the deploy command so the deployment will not echo application secrets during deployment into the CI log files when using `bcn deploy -q`.

Add quiet flag to deploy

---

.gitlab-ci.yml
Makefile
api/types_test.go

bcn cli is lacking automated build and testing. This PR introduces that. It adds a very simple test to demonstrate it and adds a CI script to run tests and attempt to compile the program.
1. Install gitlab-runner if you don't already have it
2. Try `gitlab-runner exec docker test`

Add Gitlab CI Script and Testing

---

api/types.go

Currently if you do not define CPU in your `barcelona.yml` the barcelona client will automatically fill it in with a value of 512. Since ECS tasks' CPU parameter is completely optional, this default is actually unnecessary.
This PR removes the default from being set by the client.
Refs https://github.com/degica/barcelona/issues/558

Remove default CPU value

---

api/types.go

Previously I removed the CPU default for the deploy command, but the review apps could not deploy with CPU set to 0 since bcn cli still defaulted to 0 if it was omitted from the barcelona.yml.
This change fixes that.

Omit cpu if empty for reviewapp

---

api/types.go
cmd/run.go
cmd/run_test.go

This PR allows the barcelona.yml to specify environment variables for container s started specially using the `bcn run` command. This will allow specific env vars to be set specifically for humans to operate remote services properly, instead of forcing the human to constantly use the `export` everytime the user needs to do work on the remote machine.
In this change, we add the ability to set a `run_env` for each environment in the barcelona yml file that only gets passed in when `bcn run` is used
This also adds a parameter `-E` to add/overwrite parameters from the barcelona.yml.
Refs #14 
1. Create a barcelona.yml with the following:
```
environments:
hello:
name: hello
image_name: hello_world
scheduled_tasks: []
run_env:
vars:
ABCDEF: ghi
HELLO: meow
services:
- name: web
service_type: …
```

Add run args and accept barcelona yml vars

---

cmd/run.go

This PR fixes a bug introduced in #23 where if you do not define a `run_env` section in the `barcelona.yml` it would throw a null reference error.
1. Create a `barcelona.yml` containing this:
```
environments:
hello:
name: hello
image_name: quay.io/dsiawdegica/hello
scheduled_tasks: []
services:
- name: web
service_type: web
cpu: null
memory: 256
command: sh /start.sh
listeners:
- endpoint: hello
health_check_path: /
port_mappings:
- lb_port: 80
container_port: 8080
protocol: http
```
2.Run `./bcn -d run -e hello -E FOO=bar` ew
3. Observe that there is no segfault error, and it outputs 
```
{"command":"ew","env_vars":{"FOO":"bar"},"interactive":true}
```

Fix null reference when no env vars defined in yml

---

.gitignore
cmd/login.go
config/config.go
operations/login_info_operation.go
operations/login_info_operation_test.go

This is an example of separating the CLI from the implementation to better test the CLI. Docbase post:
https://degica.docbase.io/posts/1533621
This is a refactor, but with the addition of tests!

Example separation of interface from implementation

---

api/client.go

Previously if your Barcelona server was down, or something else happens and the response is not JSON when you make an API call you get an error like
```
invalid character '<' looking for beginning of value
```
This makes absolutely no sense and confuses the user. This PR adds a message
```
Failed to parse error. Use `bcn -d` to see raw server response
```
To give the user an indication that it may not be his/her fault and provides a way for the user to find out.
Fixes #17 
1. Aim your barcelona server somewhere which gives errors by editing `~/.bcn/login` to something like
```
{"token":"abc","endpoint":"https://example.com"}
```
2. Run a command like `bcn api get /meow`
3. Observe the error says parse error failed
4. Try `bcn -d api get /meow` and observe why the response is so

Handle the 403 error a bit more properly

---

cmd/api.go
cmd/login.go
cmd/util.go
operations/api_operation.go
operations/api_operation_test.go
operations/login_info_operation.go
operations/login_info_operation_test.go
operations/operation.go
operations/operation_test.go
utils/pretty_json.go
utils/pretty_json_test.go

As a task for Refactor Tuesday I wanted to attempt doing this: https://degica.docbase.io/posts/1533621
I however learned that the document did not offer a solution for when the operation could throw errors and took parameters, so I refactored the Api Operation to start with to lay the general groundwork from which all other operations should be refactored.
This PR also includes a small refactor of prettyJSON function out to an utils package, and tests it.
This is a refactor so it should work as it always has before. Unfortunately we are still a little thin on tests, and hopefully this PR improves things for any future changes.
To reviewers: feel free to ask any questions about golang. I can jump on a call to explain things to expedite the review process, as most of us are understandably …

Refactor api operations and handle errors and add tests

---

api/heritage.go
cmd/app.go
cmd/create.go
cmd/deploy.go
cmd/district.go
cmd/endpoint.go
cmd/login.go
cmd/util.go
operations/app_operation.go
operations/app_operation_test.go
operations/operation.go
utils/are_you_sure.go

This PR moves a bunch of the `app` command out to its own operation and stubs out a bunch of things that it uses in order to enable testing on it. Yes that includes testing user input
Additionally, the following changes are made:
- Make `Print` a member of `Heritage` instead of `PrintHeritage`
- Moved User input commands into the utils package
- Create a `utils.UserInputReader` interface that allows me to stub out user input and test behaviour for various kinds of input.
As with other parts of barcelona-cli, there is some heavy golang action here so feel free to ask any questions.

More testing

---

api/client.go
api/login.go
api/types.go
cmd/login.go
cmd/ssh.go
cmd/util.go
config/config.go
operations/login_info_operation.go
operations/login_operation.go
operations/login_operation_test.go
utils/command_runner.go
utils/file_exists.go
utils/file_ops.go

This PR introduces a mechanism to login to vault. This PR has a large number of line changes, which are mostly tests (login was not tested before) and mocks to facilitate testing. If you find this PR too long, I can split it up a little more into possibly a refactor PR and test PR.
> Since this is a client, you don't need to have a bcn account, simply knowing that it sends the right requests is sufficient, though you are welcome to `kaiser up` barcelona on your local machine and following [these instructions](https://github.com/degica/barcelona/pull/605) if you wish to see everything working.
1. Simply attempt to login to vault by going: `bcn -d login https://example.com --auth vault`
2. You should be prompted to enter a github token and vault server url, just enter some random value. It …

Login vault

---

api/types.go

This PR allows reviewapps to be added to barcelona.yml
```ruby
review:
group: hello
image_name: degica/hello
services:
- service_type: web
force_ssl: true
command: sh start.sh
name: web
memory: 256
listeners:
- health_check_path: "/examplehealthcheck"
```

Add listener param to reviewapp

---

api/client.go
api/types.go
cmd/login.go
cmd/ssh.go
config/config.go
config/login.go
operations/login_info_operation.go
operations/login_info_operation_test.go

Refactor Tuesday presents another bunch of refactoring! Today we refactor the Config package to not use an ugly package init, since it no longer needs it and supplies a proper type with which to read configuration.
This PR moves config into its own object and privates the variables which are readonly anyway

Refactor Config

---

.github/workflows/release.yml

This PR automates most of the steps of releasing bcn-cli. It creates a draft PR which the maintainer can simply un-draft to release.
How to test:
1. modify the 
```
branches:
- production
```
part from `production` to `yourbranchname` and then push a new branch and see its effects.

Automate barcelona cli release

---

cmd/run.go

Fixes a null ref error that you would get if you unplugged your network while still in a bcn run
1. `bcn run -e someenv bash`
2. Pull your wifi
3. Tap enter a few times to try to communicate to it (it will break)
4. Observe that it will not throw a null reference exception

Fix a null ref error when SSH session disconnects

---

cmd/run.go

To support district-wide vault capabilities.

Use non-shallow path for oneoff

---

cmd/endpoint.go

Fixes https://github.com/degica/barcelona-cli/issues/16
If you create an endpoint and mark it as public after the endpoint name, it comes back as Public: false.
This happens because after the endpoint, if you set the flag, you can't get the value with  `public := c.Bool("public")`
So in that case I decided to show error message.
1. it should show an error if flag is set after endpoint
`bcn endpoint create --district=hello something --public`
2. it should show an error if endpoint is empty
`bcn endpoint create --district=hello`
3. make sure if this works
`bcn endpoint create --district=hello --public something`

display error when  public flag is set after endpoint

---

api/client.go

Continuation of https://github.com/degica/barcelona-cli/pull/58
I made a mistake in the condition of Auto refresh.
This caused an error to occur for existing users.
If the existing user did not execute the login command again., auto refresh should not be executed.
1. go build 
2.  `<path to the build>` run review list in your project
see if there is not error happens.

Do not auto refresh if VaultToken is empty

---

api/types.go
api/types_test.go

This PR gives you two options on how you want to format your `environment:` key on both heritages and reviewapps.
Until now you were only able to use an array to describe your environment variables
```
name: hello
image_name: quay.io/dsiawdegica/hello
scheduled_tasks: []
environment:
- name: TESTVAR
ssm_path: hello/testvar
- name: TESTVAR2
ssm_path: hello/testvar2
```
This PR allows you to use a hash instead:
```
name: hello
image_name: quay.io/dsiawdegica/hello
scheduled_tasks: []
environment:
TESTVAR:
ssm_path: hello/testvar1
TESTVAR2:
ssm_path: hello/testvar2
```
This will allow you to create composable hashes for different environments using the `<<: anchor` syntax in YAML

Hash ENV vars

---

api/client.go
api/types_test.go

If you attempt to connect somewhere that no longer exists like
`bcn login http://doghouse.snoopy` <- this used to work but now does not
and try
`bcn district list`
Instead of getting
```
Failed to parse error. Use `bcn -d` to see raw server response
invalid character '<' looking for beginning of value
```
This PR gives you
```
HTTP Error:503 Service Temporarily Unavailable
Type bcn -d <command> for details
```

Make CLI give better errors
